version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: userai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coinbase2023
      POSTGRES_DB: userai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
